spring:
  jpa:
    database: sql-server
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testfadesp
    username: sa
    password: password
    driverClassName: org.h2.Driver
server:
  port: 8989
  max-http-header-size: 48000
